// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr1cfpyBUQ-jsEs8Ea9XFInHEXyLSaELI',
    appId: '1:316774330747:web:7a5e1f7e2b29f516994dde',
    messagingSenderId: '316774330747',
    projectId: 'tamofoodapp',
    authDomain: 'tamofoodapp.firebaseapp.com',
    storageBucket: 'tamofoodapp.firebasestorage.app',
    measurementId: 'G-W9ZHMTHEDB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXbscYP7HdMUDdofCx0ME4PyydXFkTmjs',
    appId: '1:316774330747:ios:68795346c791a37d994dde',
    messagingSenderId: '316774330747',
    projectId: 'tamofoodapp',
    storageBucket: 'tamofoodapp.firebasestorage.app',
    iosBundleId: 'com.example.tamofoodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr1cfpyBUQ-jsEs8Ea9XFInHEXyLSaELI',
    appId: '1:316774330747:web:0b83ef3644d59a4e994dde',
    messagingSenderId: '316774330747',
    projectId: 'tamofoodapp',
    authDomain: 'tamofoodapp.firebaseapp.com',
    storageBucket: 'tamofoodapp.firebasestorage.app',
    measurementId: 'G-PGLEJTLCN4',
  );
}
